// AUTO-GENERATED by scripts/dataset-build/build.mjs — do not edit.
// Generated at: 2026-07-11T11:13:25.664Z
// Source: UN M49 (https://unstats.un.org/unsd/methodology/m49/)

export interface UnRegion {
  m49Code: string;       // "002" (Africa), "019" (Americas), etc.
  m49Name: string;       // "Africa", "Latin America and the Caribbean"
  parentM49Code: string | null;  // for sub-regions, points to its parent region
  regionType: "continent" | "subregion" | "intermediate";
}

export const UN_REGIONS: UnRegion[] = [
  {
    "m49Code": "142",
    "m49Name": "Asia",
    "parentM49Code": null,
    "regionType": "continent"
  },
  {
    "m49Code": "034",
    "m49Name": "Southern Asia",
    "parentM49Code": "142",
    "regionType": "subregion"
  },
  {
    "m49Code": "150",
    "m49Name": "Europe",
    "parentM49Code": null,
    "regionType": "continent"
  },
  {
    "m49Code": "154",
    "m49Name": "Northern Europe",
    "parentM49Code": "150",
    "regionType": "subregion"
  },
  {
    "m49Code": "039",
    "m49Name": "Southern Europe",
    "parentM49Code": "150",
    "regionType": "subregion"
  },
  {
    "m49Code": "002",
    "m49Name": "Africa",
    "parentM49Code": null,
    "regionType": "continent"
  },
  {
    "m49Code": "015",
    "m49Name": "Northern Africa",
    "parentM49Code": "002",
    "regionType": "subregion"
  },
  {
    "m49Code": "009",
    "m49Name": "Oceania",
    "parentM49Code": null,
    "regionType": "continent"
  },
  {
    "m49Code": "061",
    "m49Name": "Polynesia",
    "parentM49Code": "009",
    "regionType": "subregion"
  },
  {
    "m49Code": "202",
    "m49Name": "Sub-Saharan Africa",
    "parentM49Code": "002",
    "regionType": "subregion"
  },
  {
    "m49Code": "017",
    "m49Name": "Middle Africa",
    "parentM49Code": "202",
    "regionType": "intermediate"
  },
  {
    "m49Code": "019",
    "m49Name": "Americas",
    "parentM49Code": null,
    "regionType": "continent"
  },
  {
    "m49Code": "419",
    "m49Name": "Latin America and the Caribbean",
    "parentM49Code": "019",
    "regionType": "subregion"
  },
  {
    "m49Code": "029",
    "m49Name": "Caribbean",
    "parentM49Code": "419",
    "regionType": "intermediate"
  },
  {
    "m49Code": "005",
    "m49Name": "South America",
    "parentM49Code": "419",
    "regionType": "intermediate"
  },
  {
    "m49Code": "145",
    "m49Name": "Western Asia",
    "parentM49Code": "142",
    "regionType": "subregion"
  },
  {
    "m49Code": "053",
    "m49Name": "Australia and New Zealand",
    "parentM49Code": "009",
    "regionType": "subregion"
  },
  {
    "m49Code": "155",
    "m49Name": "Western Europe",
    "parentM49Code": "150",
    "regionType": "subregion"
  },
  {
    "m49Code": "151",
    "m49Name": "Eastern Europe",
    "parentM49Code": "150",
    "regionType": "subregion"
  },
  {
    "m49Code": "013",
    "m49Name": "Central America",
    "parentM49Code": "419",
    "regionType": "intermediate"
  },
  {
    "m49Code": "011",
    "m49Name": "Western Africa",
    "parentM49Code": "202",
    "regionType": "intermediate"
  },
  {
    "m49Code": "021",
    "m49Name": "Northern America",
    "parentM49Code": "019",
    "regionType": "subregion"
  },
  {
    "m49Code": "018",
    "m49Name": "Southern Africa",
    "parentM49Code": "202",
    "regionType": "intermediate"
  },
  {
    "m49Code": "014",
    "m49Name": "Eastern Africa",
    "parentM49Code": "202",
    "regionType": "intermediate"
  },
  {
    "m49Code": "035",
    "m49Name": "South-eastern Asia",
    "parentM49Code": "142",
    "regionType": "subregion"
  },
  {
    "m49Code": "030",
    "m49Name": "Eastern Asia",
    "parentM49Code": "142",
    "regionType": "subregion"
  },
  {
    "m49Code": "054",
    "m49Name": "Melanesia",
    "parentM49Code": "009",
    "regionType": "subregion"
  },
  {
    "m49Code": "057",
    "m49Name": "Micronesia",
    "parentM49Code": "009",
    "regionType": "subregion"
  },
  {
    "m49Code": "143",
    "m49Name": "Central Asia",
    "parentM49Code": "142",
    "regionType": "subregion"
  }
];
